### ISSUE TITLE
Move discussion on "pass" from module 1 to module 3

### ISSUE THREAD

**Issue by jgonggrijp** [CentreForDigitalHumanities/programming-in-python#2]
Currently, module 1 introduces `print`, a few values, comments and `pass`. While I think that contrasting `pass` with values and comments is instructive, the keyword seems rather useless in this context. @oktaal pointed out that module 3 would be a more logical place to introduce `pass`, when indented blocks enter the scene. I agree.

**Comment by jgonggrijp** [comment]
Implemented in the May 2024 edition on Google Drive. Will commit later.

**Comment by ar-jan** [comment]
Completed in #14.
