### ISSUE TITLE
Split module 7 in two parts

### ISSUE THREAD

**Issue by jgonggrijp** [CentreForDigitalHumanities/programming-in-python#3]
After thinking more about it, I think module 7 is currently too heavy. I would like to split it in two parts:

- Up to and including exercise 7.2: this introduces basic functions and is sufficient to understand modules 8-11. It should remain module number 7.
- The rest: this is the more advanced stuff. I would make this module 12.

**Comment by jgonggrijp** [comment]
This is a work in progress in the Google Drive for the May 2024 edition.

**Comment by jgonggrijp** [comment]
Was finished in the Google Drive. To be committed.

**Comment by ar-jan** [comment]
Completed in #14.
