### ISSUE TITLE
Enrich exercises for modules 9-11

### ISSUE THREAD

**Issue by jgonggrijp** [CentreForDigitalHumanities/programming-in-python#4]
These modules could use

- more easy exercises, to warm up the course participants
- separate bonus exercises (possibly including some of the existing exercises), for time management and catering to different learning speeds

**Comment by jgonggrijp** [comment]
I added more exercises to module 9 in the Google Drive for the May 2024 edition. Answers still have to be added.

**Comment by jgonggrijp** [comment]
Answers for module 9 as well as exercises and answers for module 10 were also added. To be committed.

**Comment by ar-jan** [comment]
Completed in #14.
