### ISSUE TITLE
Add "Tips" and "Life after the course" notebooks to the repo

### ISSUE THREAD

**Issue by jgonggrijp** [CentreForDigitalHumanities/programming-in-python#6]
I wrote those notebooks already for the first edition of the course, but they have not made it into the repo yet.

**Comment by lukavdplas** [comment]
I think you can recover them from this version:

https://github.com/UUDigitalHumanitieslab/programming-in-python/tree/580e86f6f7831ec145f9d8ce031e056405bd61ca
